### Implementation of NeuralNet2

In [1]:
from NeuralNet2 import Layer, NeuralNet
import numpy as np

In [2]:
inputs = [1,2,3,3,3,4]

In [7]:
layer1 = Layer(input_count=len(inputs) , node_count=4, activations=[1,1,1,1])
layer1.build_layer()

layer2 = Layer(input_count=4 , node_count=2, activations=[1,1])
layer2.build_layer()

In [8]:
layers = [layer1, layer2]

In [9]:
network = NeuralNet(layers, inputs)
network.fire_net()

[5.57058339 6.04464438 4.69303666 9.21888197] (4,)
[1 1 1 1] (4,)
[2.18629684 2.01140687] (2,)
[1 1] (2,)


In [10]:
network.output

array([1.12654726, 1.15446819])